wx:
  appid: wx034835fc30d8903b
  appsecret: 301641c761c1da43e5d886f90483061a
  token: wang...
  callback: http://17mb642884.51mypc.cn/wxCallBack
  add_menu_url: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
  access_token_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wx.appid}&secret=${wx.appsecret}
  code_url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${wx.appid}&redirect_uri=${wx.callback}&response_type=code&scope=snsapi_userinfo&state=STATE#wechat_redirect
  webpage_access_token_url: https://api.weixin.qq.com/sns/oauth2/access_token?appid=${wx.appid}&secret=${wx.appsecret}&code=CODE&grant_type=authorization_code
  userinfo_url: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
  qing_url: http://api.qingyunke.com/api.php?key=free&appid=0&msg=MSG
